#ifndef ENEMY_UTILS_HH
#define ENEMY_UTILS_HH
#include "entity.hh"

#include <array>
#include <string_view>

namespace potmaker::constants {

// Enemy names generated by DeepSeek to match the ingredient types
/*
 * PROMPT USED:
 * Hey there! in a similar fashion to how these names have been generated, I
 * need to do something similar but with entity names. Instead of ingredient
 * names, generate the code for an array of 10 names for each type of enemy
 * (same types as ingredients)
 *
 * [CODE FROM ingredient_utils.hh]
 */

constexpr std::array<std::string_view, 10> flaming_enemy_names{
    "Blaze Imp",      "Ember Hound",        "Pyre Drake",    "Scorchfiend",
    "Magma Lurker",   "Inferno Sprite",     "Sunflare Wisp", "Cinderback",
    "Flame Revenant", "Dragonkin Berserker"};

constexpr std::array<std::string_view, 10> chilling_enemy_names{
    "Frost Wraith",      "Glacial Stalker", "Shiverling",
    "Permafrost Horror", "Arctic Ghoul",    "Icewyrm Hatchling",
    "Snowcloak Phantom", "Boreal Revenant", "Chillfiend",
    "Winter's Maw"};

constexpr std::array<std::string_view, 10> poisonous_enemy_names{
    "Venom Maw",      "Nightshade Stalker", "Serpentkin",   "Rotspawn",
    "Widow's Horror", "Festering Ooze",     "Mire Creeper", "Deathcap Shambler",
    "Toxin Fiend",    "Plague Carrier"};

constexpr std::array<std::string_view, 10> withering_enemy_names{
    "Wither Specter", "Graveborn",      "Bone Reaver",  "Necrotic Shade",
    "Dusk Stalker",   "Cursed Husk",    "Hollow Wight", "Eclipse Phantom",
    "Sorrowfiend",    "Oblivion Walker"};

constexpr std::array<std::string_view, 10> healing_enemy_names{
    "Sunwarden",      "Angel's Bane", "Lifedrinker",         "Sacred Defiler",
    "Mending Horror", "Heartripper",  "Celestial Corruptor", "Soothing Menace",
    "Purebane",       "Harmony's Foe"};

constexpr std::array<std::string_view, 10> regenerative_enemy_names{
    "Swiftskin",        "Rejuvenation Horror",
    "Vital Leech",      "Everflow Abomination",
    "Renewal Fiend",    "Vigor Thief",
    "Phoenix Scourge",  "Brimming Terror",
    "Resilience Eater", "Fleshweaver"};

constexpr std::array<std::string_view, 10> protective_enemy_names{
    "Aegis Golem",        "Guardian Corruptor", "Ironhide",
    "Bastion Colossus",   "Wardbreaker",        "Shimmerfiend",
    "Fortitude Devourer", "Bulwark Behemoth",   "Sentinel's Bane",
    "Diamondclaw"};

constexpr std::array<std::string_view, 10> strengthening_enemy_names{
    "Titan's Scourge",    "Fury Incarnate",        "Mightfiend",
    "Storm Brute",        "Valor Reaver",          "Giantkin",
    "Thunderclaw",        "Adamantite Juggernaut", "Berserker Wraith",
    "Overgrowth Behemoth"};

constexpr std::array<std::string_view, 10> cleansing_enemy_names{
    "Purity Defiler", "Cleansing Bane",     "Sanctified Horror",
    "Voidspawn",      "Purgefiend",         "Clarity Corruptor",
    "Lighteater",     "Aether Abomination", "Purifying Scourge",
    "Dawn's End"};

constexpr std::array<std::string_view, 10> joker_enemy_names{
    "Chaos Imp",        "Wildkin",
    "Prismatic Horror", "Fickle Fiend",
    "Madcap Mimic",     "Whimsy Wretch",
    "Paradox Entity",   "Unstable Abberation",
    "Trickster Demon",  "Riddlefiend"};

[[nodiscard]] auto generate_enemy(int stage) -> enemy *;

} // namespace potmaker::constants

#endif // ENEMY_UTILS_HH