#ifndef INGREDIENT_UTILS_HH
#define INGREDIENT_UTILS_HH

#include "ingredient.hh"

#include <array>
#include <string_view>

namespace potmaker::constants {

// These names were generated by DeepSeek. I'm not that creative.
/*
 * PROMPT USED:
 * Hey dude! I am making a really tiny game in which you mix ingredients into
 * potions. I need some names; can you help me fill these arrays with your
 * ideas?
 */
constexpr std::array<std::string_view, 10> flaming_ingredient_names{
    "Blaze Pepper", "Ember Root",         "Phoenix Feather", "Scorchbloom",
    "Molten Shard", "Inferno Berry",      "Sunscale Powder", "Cinder Moss",
    "Flame Nectar", "Dragon's Breath Pod"};

constexpr std::array<std::string_view, 10> chilling_ingredient_names{
    "Frostleaf",    "Glacial Lotus", "Shiverthorn",      "Permafrost Seed",
    "Arctic Resin", "Icewyrm Scale", "Snowcap Mushroom", "Boreal Essence",
    "Chillvine",    "Winter's Tear"};

constexpr std::array<std::string_view, 10> poisonous_ingredient_names{
    "Venomroot",    "Nightshade Berry", "Serpent's Kiss", "Rotbloom",
    "Widow's Bane", "Festering Spore",  "Mire Sludge",    "Deathcap Fungus",
    "Toxin Thorn",  "Plague Dust"};

constexpr std::array<std::string_view, 10> withering_ingredient_names{
    "Wither Moss", "Gravebloom",     "Bone Ash",    "Necrotic Sap",
    "Duskthorn",   "Cursed Residue", "Hollow Seed", "Eclipse Petal",
    "Sorrowroot",  "Oblivion Dust"};

constexpr std::array<std::string_view, 10> healing_ingredient_names{
    "Sunpetal",     "Angel's Balm", "Lifewort",       "Sacred Dew",
    "Mending Moss", "Heartbloom",   "Celestial Root", "Soothing Nectar",
    "Pureleaf",     "Harmony Shard"};

constexpr std::array<std::string_view, 10> regenerative_ingredient_names{
    "Swiftgrass",      "Rejuvenation Pod", "Vital Essence", "Everflow Sap",
    "Renewal Spore",   "Vigorroot",        "Phoenix Tear",  "Brimming Heart",
    "Resilience Seed", "Flowermend"};

constexpr std::array<std::string_view, 10> protective_ingredient_names{
    "Aegis Bark",       "Guardian Shard", "Ironbloom",      "Bastion Seed",
    "Wardroot",         "Shimmerhide",    "Fortitude Dust", "Bulwark Moss",
    "Sentinel's Resin", "Diamondthorn"};

constexpr std::array<std::string_view, 10> strengthening_ingredient_names{
    "Titan's Blood",     "Fury Essence",    "Mightroot",    "Storm Core",
    "Valor Nectar",      "Giant's Grasp",   "Thunderbloom", "Adamantite Powder",
    "Berserker's Resin", "Overgrowth Spore"};

constexpr std::array<std::string_view, 10> cleansing_ingredient_names{
    "Purity Lotus",   "Clearseed",    "Sanctified Water", "Voidbane Leaf",
    "Purgeberry",     "Clarity Dust", "Lightroot",        "Aether Bloom",
    "Purifying Salt", "Dawn Essence"};

constexpr std::array<std::string_view, 10> joker_ingredient_names{
    "Chaos Nectar",     "Wildroot",    "Prismatic Pod", "Fickle Shard",
    "Madcap Fungus",    "Whimsy Dust", "Paradox Bloom", "Unstable Core",
    "Trickster's Tear", "Riddlethorn"};

[[nodiscard]] auto generate_ingredient(int stage) -> ingredient *;

} // namespace potmaker::constants

#endif // INGREDIENT_UTILS_HH
